services:
  gemini-web:
    image: gemini-webui
    build: .
    ports:
      - "5000:5000"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_BIND_USER_DN=${LDAP_BIND_USER_DN}
      - LDAP_BIND_PASS=${LDAP_BIND_PASS}
      - LDAP_AUTHORIZED_GROUP=${LDAP_AUTHORIZED_GROUP}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
