[pytest]
addopts = --timeout=60
timeout_func_only = false
timeout_method = signal
markers =
    prone_to_timeout: mark a test as prone to hanging, requiring strict timeout enforcement
    timeout: mark a test to timeout after a given number of seconds
filterwarnings =
    ignore:tagMap is deprecated. Please use TAG_MAP instead.:DeprecationWarning
    ignore:typeMap is deprecated. Please use TYPE_MAP instead.:DeprecationWarning
