sonar.projectKey=adamoutler_gemini-webui
sonar.organization=adamoutler
sonar.projectName=gemini-webui
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11,3.12
sonar.exclusions=**/__pycache__/**,**/node_modules/**,src/static/js/libs/**,**/__init__.py,tests/**
sonar.test.inclusions=tests/**

sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18,e19,e20,e21,e22,e23,e24,e25,e26,e27,e28,e29,e30,e31,e32,e33,e34,e35,e36,e37,e38,e39,e40,e41,e42,e43,e44,e45,e46,e47,e48,e49,e50
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=src/config.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S4502
sonar.issue.ignore.multicriteria.e2.resourceKey=src/docs_server.py
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S5443
sonar.issue.ignore.multicriteria.e3.resourceKey=src/services/process_engine.py
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S5852
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e5.ruleKey=javascript:S2245
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e6.ruleKey=python:S4828
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e7.ruleKey=python:S5443
sonar.issue.ignore.multicriteria.e7.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e8.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e8.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e9.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e9.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e10.ruleKey=javascript:S2486
sonar.issue.ignore.multicriteria.e10.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e11.ruleKey=javascript:S6582
sonar.issue.ignore.multicriteria.e11.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e12.ruleKey=javascript:S7781
sonar.issue.ignore.multicriteria.e12.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e13.ruleKey=javascript:S1874
sonar.issue.ignore.multicriteria.e13.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e14.ruleKey=javascript:S7763
sonar.issue.ignore.multicriteria.e14.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e15.ruleKey=javascript:S7780
sonar.issue.ignore.multicriteria.e15.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e16.ruleKey=javascript:S6861
sonar.issue.ignore.multicriteria.e16.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e17.ruleKey=javascript:S2004
sonar.issue.ignore.multicriteria.e17.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e18.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e18.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e19.ruleKey=css:S7924
sonar.issue.ignore.multicriteria.e19.resourceKey=**/*.css
sonar.issue.ignore.multicriteria.e20.ruleKey=python:S5914
sonar.issue.ignore.multicriteria.e20.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e21.ruleKey=javascript:S4138
sonar.issue.ignore.multicriteria.e21.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e22.ruleKey=javascript:S6660
sonar.issue.ignore.multicriteria.e22.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e23.ruleKey=javascript:S1128
sonar.issue.ignore.multicriteria.e23.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e24.ruleKey=javascript:S1481
sonar.issue.ignore.multicriteria.e24.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e25.ruleKey=python:S112
sonar.issue.ignore.multicriteria.e25.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e26.ruleKey=javascript:S7735
sonar.issue.ignore.multicriteria.e26.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e27.ruleKey=javascript:S7741
sonar.issue.ignore.multicriteria.e27.resourceKey=**/*.js

sonar.issue.ignore.multicriteria.e28.ruleKey=Web:S6853
sonar.issue.ignore.multicriteria.e28.resourceKey=**/*.html
sonar.issue.ignore.multicriteria.e29.ruleKey=python:S108
sonar.issue.ignore.multicriteria.e29.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e30.ruleKey=python:S1172
sonar.issue.ignore.multicriteria.e30.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e31.ruleKey=python:S6353
sonar.issue.ignore.multicriteria.e31.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e32.ruleKey=javascript:S6635
sonar.issue.ignore.multicriteria.e32.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e33.ruleKey=javascript:S2703
sonar.issue.ignore.multicriteria.e33.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e34.ruleKey=javascript:S7721
sonar.issue.ignore.multicriteria.e34.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e35.ruleKey=javascript:S6353
sonar.issue.ignore.multicriteria.e35.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e36.ruleKey=javascript:S3358
sonar.issue.ignore.multicriteria.e36.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e37.ruleKey=javascript:S1871
sonar.issue.ignore.multicriteria.e37.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e38.ruleKey=javascript:S125
sonar.issue.ignore.multicriteria.e38.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e39.ruleKey=python:S1871
sonar.issue.ignore.multicriteria.e39.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e40.ruleKey=javascript:S4043
sonar.issue.ignore.multicriteria.e40.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e41.ruleKey=css:S4658
sonar.issue.ignore.multicriteria.e41.resourceKey=**/*.css
sonar.issue.ignore.multicriteria.e42.ruleKey=javascript:S7754
sonar.issue.ignore.multicriteria.e42.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e43.ruleKey=javascript:S7762
sonar.issue.ignore.multicriteria.e43.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e44.ruleKey=python:S2772
sonar.issue.ignore.multicriteria.e44.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e45.ruleKey=javascript:S6535
sonar.issue.ignore.multicriteria.e45.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e46.ruleKey=python:S1481
sonar.issue.ignore.multicriteria.e46.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e47.ruleKey=python:S1066
sonar.issue.ignore.multicriteria.e47.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e48.ruleKey=javascript:S7755
sonar.issue.ignore.multicriteria.e48.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e49.ruleKey=javascript:S3863
sonar.issue.ignore.multicriteria.e49.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e50.ruleKey=javascript:S1854
sonar.issue.ignore.multicriteria.e50.resourceKey=**/*.js
