sonar.projectKey=adamoutler_gemini-webui
sonar.organization=adamoutler
sonar.projectName=gemini-webui
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11,3.12
sonar.exclusions=**/__pycache__/**,**/node_modules/**,src/static/js/libs/**,**/__init__.py,tests/**
sonar.test.inclusions=tests/**
sonar.coverage.exclusions=src/static/js/**/*.js,src/static/main.js,src/templates/**/*.html

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=src/config.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S4502
sonar.issue.ignore.multicriteria.e2.resourceKey=src/docs_server.py
