import pytest
import os
from unittest.mock import patch, MagicMock
from src.config import get_config_paths


@pytest.mark.timeout(60)
def test_get_config_paths_env_override():
    with patch.dict(os.environ, {"DATA_DIR": "/custom/data"}):
        d, c, s = get_config_paths()
        # It should prefer the env var if it exists/is writable,
        # but the function also checks for existence.
        assert isinstance(d, str)


@pytest.mark.timeout(60)
def test_init_app_full(test_data_dir):
    from src.app import app
    import src.config

    app.config["DATA_DIR"] = str(test_data_dir)
    src.config.app_config.init_config(str(test_data_dir))
    app.config["TESTING"] = True

    with patch("src.app.os.makedirs") as mock_mkdir, patch(
        "src.app.os.chmod"
    ) as mock_chmod, patch("src.app.subprocess.run") as mock_run:
        # Simulate key generation needed
        mock_run.return_value = MagicMock(returncode=0)

        from src.app import init_app

        init_app()

        # Verify key generation was attempted if file missing
        # (This depends on actual existence in test_data_dir)
        pass


@pytest.mark.timeout(60)
def test_ssh_key_rotation_logic(test_data_dir):
    from src.app import app

    app.config["DATA_DIR"] = str(test_data_dir)
    import src.config

    src.config.app_config.init_config(str(test_data_dir))
    ssh_dir = os.path.join(str(test_data_dir), ".ssh")
    os.makedirs(ssh_dir, exist_ok=True)
    key_path = os.path.join(ssh_dir, "id_ed25519")

    with open(key_path, "w") as f:
        f.write("old key")
    with open(key_path + ".pub", "w") as f:
        f.write("old public key")

    with patch("src.app.subprocess.run") as mock_run:

        def side_effect(*args, **kwargs):
            # Create the files that the code expects to be generated by ssh-keygen
            with open(key_path, "w") as f:
                f.write("new key")
            with open(key_path + ".pub", "w") as f:
                f.write("new public key")
            return MagicMock(returncode=0)

        mock_run.side_effect = side_effect

        # Mock the rotate_instance_key API call indirectly or directly
        from src.routes.host_keys import (
            rotate_instance_key,
        )  # We need a request context for API calls

        with patch.dict(
            os.environ,
            {"BYPASS_AUTH_FOR_TESTING": "true", "DATA_DIR": str(test_data_dir)},
        ):
            with app.test_request_context():
                response = rotate_instance_key()
                # Flask routes called directly return (body, status) or response object
                # depending on implementation. Our code returns (jsonify, 200) usually
                # OR a Response object if jsonify is returned.
                if isinstance(response, tuple):
                    assert response[1] == 200
                else:
                    assert response.status_code == 200

                    mock_run.assert_called()
                    # Verify backup was made (format: id_ed25519.<timestamp>.bak)
                    files = os.listdir(ssh_dir)
                    assert any(".bak" in f and "id_ed25519" in f for f in files)
                    assert any(".pub.bak" in f and "id_ed25519" in f for f in files)
